import { expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { test, registerAndLogin, controlledToday } from "./helpers";

test("simulado com cronômetro, correção, dashboard e exclusão", async ({ page }, testInfo) => {
  await registerAndLogin(page, "mock-exam");
  await page.getByRole("navigation", { name: "Navegação principal" }).getByRole("link", { name: "Simulados", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Seu próximo simulado começa aqui" })).toBeVisible();
  await page.getByRole("link", { name: "Novo simulado" }).click();
  await page.getByLabel("Total de questões").fill("100");
  await page.getByRole("button", { name: "Salvar simulado" }).click();
  await expect(page).toHaveURL(/\/simulados\/[a-f0-9-]+$/);
  const detailsUrl = page.url();
  await page.getByRole("button", { name: "Iniciar simulado" }).click();
  await expect(page.getByRole("button", { name: "Finalizar simulado" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "Finalizar simulado" })).toBeVisible();
  await page.getByRole("button", { name: "Finalizar simulado" }).click();
  await expect(page.getByText("Correção pendente.", { exact: false })).toBeVisible();
  await page.getByRole("link", { name: "Editar simulado" }).click();
  await page.getByLabel("Acertos", { exact: true }).fill("30");
  await expect(page.getByLabel("Erros (calculados)")).toHaveValue("70");
  await page.getByLabel("Sentimento (opcional)").selectOption("CALM");
  await page.getByLabel("Comentário (opcional)").fill("Mantive a calma e terminei a prova.");
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("simulado-edicao.png"), fullPage: true });
  await page.getByRole("button", { name: "Salvar simulado" }).click();
  await expect(page).toHaveURL(detailsUrl);
  await expect(page.getByText("30,0%", { exact: true })).toBeVisible();
  await expect(page.getByText("Tranquilo", { exact: true })).toBeVisible();
  await page.goto(`/dashboard?period=all&today=${controlledToday}`);
  const tabs = page.getByRole("navigation", { name: "Abas do dashboard" });
  await expect(tabs.getByRole("link", { name: "Sessões de estudo" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("region", { name: "Desempenho nos simulados" })).toHaveCount(0);
  await page.getByRole("link", { name: "Doutrina", exact: true }).click();
  await expect(page.getByRole("link", { name: "Doutrina", exact: true })).toHaveAttribute("aria-current", "page");
  await tabs.getByRole("link", { name: "Simulados", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(tabs.getByRole("link", { name: "Simulados", exact: true })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("navigation", { name: "Filtrar tipo de questão" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Novo simulado", exact: true })).toBeVisible();
  await page.getByRole("link", { name: "90 dias", exact: true }).click();
  await expect(page).toHaveURL(/period=90d.*tab=simulados/);
  await page.reload();
  await expect(tabs.getByRole("link", { name: "Simulados", exact: true })).toHaveAttribute("aria-current", "page");
  await tabs.getByRole("link", { name: "Sessões de estudo" }).click();
  await expect(page.getByRole("link", { name: "Doutrina", exact: true })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("link", { name: "90 dias", exact: true })).toHaveAttribute("aria-current", "page");
  await tabs.getByRole("link", { name: "Simulados", exact: true }).click();
  const section = page.getByRole("region", { name: "Desempenho nos simulados" });
  await expect(section.getByText("30,0% · 30 de 100")).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("dashboard-simulados.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto(detailsUrl);
  await page.getByRole("button", { name: "Excluir", exact: true }).click();
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  await expect(page.getByRole("button", { name: "Excluir", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Excluir", exact: true }).click();
  await page.getByRole("button", { name: "Confirmar exclusão" }).click();
  await expect(page).toHaveURL(/\/simulados$/);
  await expect(page.getByRole("heading", { name: "Seu próximo simulado começa aqui" })).toBeVisible();
});

test("simulado histórico com horários opcionais e correção por erros", async ({ page }) => {
  await registerAndLogin(page, "historical-exam");
  await page.goto("/simulados/new");
  await page.getByLabel("Já realizei este simulado").check();
  await page.getByLabel("Total de questões").fill("100");
  await page.getByLabel("Qual resultado deseja informar?").selectOption("wrongAnswers");
  await page.getByLabel("Erros", { exact: true }).fill("30");
  await expect(page.getByLabel("Acertos (calculados)")).toHaveValue("70");
  await page.getByLabel("Data e hora de início").fill("2025-04-09T23:30");
  await page.getByLabel("Data e hora de fim").fill("2025-04-10T01:00");
  await page.getByRole("button", { name: "Salvar simulado" }).click();
  await expect(page.getByRole("timer")).toHaveText("01:30:00");
  await expect(page.getByText("70,0%", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Editar simulado" }).click();
  await page.getByLabel("Data e hora de início").fill("");
  await page.getByLabel("Data e hora de fim").fill("");
  await page.getByLabel("Acertos", { exact: true }).fill("");
  await page.getByRole("button", { name: "Salvar simulado" }).click();
  await expect(page.getByRole("timer")).toHaveText("Tempo não informado");
  await expect(page.getByText("Correção pendente.", { exact: false })).toBeVisible();
  await page.goto("/dashboard?period=all&tab=simulados");
  const section = page.getByRole("region", { name: "Desempenho nos simulados" });
  await expect(section.getByText("Aguardando correção", { exact: true })).toBeVisible();
  await expect(section.getByRole("progressbar")).toHaveCount(0);
});
